/**
 * CELSON Shop — Price Configuration
 * Auto-generated by admin panel
 */

var CELSON_CONFIG = {
  adminUser: 'Celsonbetty',
  adminPass: '86880707',
  exchangeRate: 6.6
};

var PRICES_RMB = {
  'gyp-std-12': 35.00,
  'gyp-mr-12': 40.00,
  'gyp-fr-12': 22.50,
  'ply-18': 132.00,
  'mdf-18': 105.00,
  'osb-15': 87.00,
  'wpc-wall-8': 52.50,
  'uv-marble-8': 72.00,
  'pvc-ceiling-7': 33.00,
  'mineral-ceiling-15': 15.75,
  't-grid-38': 36.00,
  'metal-stud-75': 30.00,
  'cs-board-8': 33.00,
  'cs-board-12': 55.50,
  'wpc-deck-140': 90.00,
  'wpc-clad-150': 66.00,
  'joint-compound-20': 48.00,
  'drywall-screw-25': 22.50,
  'rockwool-50': 51.00,
  'xps-50': 37.50
};
