/**
 * CELSON Shop — Product Metadata
 * Auto-managed by admin panel
 * DO NOT EDIT BY HAND
 */
var ALL_PRODUCTS = [
  {"id":"gyp-std-12","category":"Gypsum Boards","name":"Standard Gypsum Board 12mm","spec":"1200 &times; 2400mm &middot; Ivory paper-faced","extra":"Min. 200 m&sup2; &middot; Shipped from Guangdong","unit":"/m&sup2; EXW","minQty":200,"thumb":"assets/shop/shop-gyp-std-12.webp","hidden":false,"order":1},
  {"id":"gyp-mr-12","category":"Gypsum Boards","name":"Moisture-Resistant Gypsum Board 12mm","spec":"1200 &times; 2400mm &middot; Green water-repellent","extra":"Min. 150 m&sup2; &middot; Shipped from Guangdong","unit":"/m&sup2; EXW","minQty":150,"thumb":"assets/shop/shop-gyp-mr-12.webp","hidden":false,"order":2},
  {"id":"gyp-fr-12","category":"Gypsum Boards","name":"Fire-Rated Gypsum Board 12mm","spec":"1200 &times; 2400mm &middot; Glass fiber reinforced","extra":"Min. 150 m&sup2; &middot; Shipped from Guangdong","unit":"/m&sup2; EXW","minQty":150,"thumb":"assets/shop/shop-gyp-fr-12.webp","hidden":false,"order":3},
  {"id":"ply-18","category":"Sheet Boards","name":"Commercial Plywood 18mm","spec":"1220 &times; 2440mm &middot; Hardwood core","extra":"Min. 100 sheets &middot; Shipped from Shandong","unit":"/sheet EXW","minQty":100,"thumb":"assets/shop/shop-ply-18.webp","hidden":false,"order":4},
  {"id":"mdf-18","category":"Sheet Boards","name":"MDF Board 18mm — E1 Grade","spec":"1220 &times; 2440mm &middot; Smooth sanded surface","extra":"Min. 80 sheets &middot; Shipped from Shandong","unit":"/sheet EXW","minQty":80,"thumb":"assets/shop/shop-mdf-18.webp","hidden":false,"order":5},
  {"id":"osb-15","category":"Sheet Boards","name":"OSB Board 15mm — Structural","spec":"1220 &times; 2440mm &middot; Oriented strand","extra":"Min. 80 sheets &middot; Shipped from Jiangsu","unit":"/sheet EXW","minQty":80,"thumb":"assets/shop/shop-osb-15.webp","hidden":false,"order":6},
  {"id":"wpc-wall-8","category":"Wall Panels","name":"WPC Wall Panel 8mm — Wood Grain","spec":"160 &times; 2900mm &middot; 3D wood texture","extra":"Min. 100 m&sup2; &middot; Shipped from Zhejiang","unit":"/m&sup2; EXW","minQty":100,"thumb":"assets/shop/shop-wpc-wall-8.webp","hidden":false,"order":7},
  {"id":"uv-marble-8","category":"Wall Panels","name":"UV Marble Wall Panel 8mm","spec":"1220 &times; 2440mm &middot; High-gloss finish","extra":"Min. 80 m&sup2; &middot; Shipped from Zhejiang","unit":"/m&sup2; EXW","minQty":80,"thumb":"assets/shop/shop-uv-marble-8.webp","hidden":false,"order":8},
  {"id":"pvc-ceiling-7","category":"Wall Panels","name":"PVC Wall Panel 7mm — Solid Color","spec":"250 &times; 3000mm &middot; Matte white","extra":"Min. 150 m&sup2; &middot; Shipped from Zhejiang","unit":"/m&sup2; EXW","minQty":150,"thumb":"assets/shop/shop-pvc-ceiling-7.webp","hidden":false,"order":9},
  {"id":"mineral-ceiling-15","category":"Ceiling & Framing","name":"Mineral Fiber Ceiling Tile 15mm","spec":"600 &times; 600mm &middot; Acoustic","extra":"Min. 200 pcs &middot; Shipped from Hebei","unit":"/pc EXW","minQty":200,"thumb":"assets/shop/shop-mineral-ceiling-15.webp","hidden":false,"order":10},
  {"id":"t-grid-38","category":"Ceiling & Framing","name":"T-Grid Main Tee 38mm","spec":"38 &times; 24mm &middot; Hot-dip galvanized","extra":"Min. 500 pcs &middot; Shipped from Hebei","unit":"/pc EXW","minQty":500,"thumb":"assets/shop/shop-t-grid-38.webp","hidden":false,"order":11},
  {"id":"metal-stud-75","category":"Ceiling & Framing","name":"Metal Stud 75mm — Galvanized","spec":"75 &times; 45mm &middot; 0.6mm thick","extra":"Min. 300 pcs &middot; Shipped from Hebei","unit":"/pc EXW","minQty":300,"thumb":"assets/shop/shop-metal-stud-75.webp","hidden":false,"order":12},
  {"id":"cs-board-8","category":"Calcium Silicate","name":"Calcium Silicate Board 8mm","spec":"1220 &times; 2440mm &middot; Non-asbestos","extra":"Min. 100 sheets &middot; Shipped from Guangdong","unit":"/sheet EXW","minQty":100,"thumb":"assets/shop/shop-cs-board-8.webp","hidden":false,"order":13},
  {"id":"cs-board-12","category":"Calcium Silicate","name":"Calcium Silicate Board 12mm — HD","spec":"1220 &times; 2440mm &middot; High density","extra":"Min. 80 sheets &middot; Shipped from Guangdong","unit":"/sheet EXW","minQty":80,"thumb":"assets/shop/shop-cs-board-12.webp","hidden":false,"order":14},
  {"id":"wpc-deck-140","category":"Outdoor & Decking","name":"WPC Decking 140mm — Solid","spec":"140 &times; 25mm &middot; Co-extrusion","extra":"Min. 50 m&sup2; &middot; Shipped from Zhejiang","unit":"/m&sup2; EXW","minQty":50,"thumb":"assets/shop/shop-wpc-deck-140.webp","hidden":false,"order":15},
  {"id":"wpc-clad-150","category":"Outdoor & Decking","name":"WPC Cladding 150mm — Hollow","spec":"150 &times; 20mm &middot; UV resistant","extra":"Min. 50 m&sup2; &middot; Shipped from Zhejiang","unit":"/m&sup2; EXW","minQty":50,"thumb":"assets/shop/shop-wpc-clad-150.webp","hidden":false,"order":16},
  {"id":"joint-compound-20","category":"Accessories","name":"Joint Compound 20kg — Ready-Mix","spec":"20kg bucket &middot; Premixed","extra":"Min. 50 pcs &middot; Shipped from Guangdong","unit":"/pc EXW","minQty":50,"thumb":"assets/shop/shop-joint-compound-20.webp","hidden":false,"order":17},
  {"id":"drywall-screw-25","category":"Accessories","name":"Drywall Screw 25mm — Phosphated","spec":"3.5 &times; 25mm &middot; 1000pcs/box","extra":"Min. 20 boxes &middot; Shipped from Hebei","unit":"/box EXW","minQty":20,"thumb":"assets/shop/shop-drywall-screw-25.webp","hidden":false,"order":18},
  {"id":"rockwool-50","category":"Insulation","name":"Rock Wool Board 50mm — 120kg/m&sup3;","spec":"1200 &times; 600mm &middot; 120kg/m&sup3;","extra":"Min. 100 m&sup2; &middot; Shipped from Hebei","unit":"/m&sup2; EXW","minQty":100,"thumb":"assets/shop/shop-rockwool-50.webp","hidden":false,"order":19},
  {"id":"xps-50","category":"Insulation","name":"XPS Board 50mm — 35kg/m&sup3;","spec":"1200 &times; 600mm &middot; 35kg/m&sup3;","extra":"Min. 100 m&sup2; &middot; Shipped from Jiangsu","unit":"/m&sup2; EXW","minQty":100,"thumb":"assets/shop/shop-xps-50.webp","hidden":false,"order":20}
];
